[
    {
        "itemName": "1906 Race Riot",
        "itemSubhead": "Racial Violence Prompts Migration",
        "itemDescription": "Uncomfortable with the city’s growing Black population and increased visibility, white Atlantans launched an orgy of violence after the city's main newspapers printed false rumors of Black men raping white women. Rioters targeted prosperous Black-owned downtown businesses like barbershops, as well as establishments along the Decatur Avenue entertainment strip, some of which served an interracial clientele.  At least 25 Blacks (and 2 whites) were killed in the violence which lasted for nearly three days.  Although at least one Eastside Black neighborhood organized a successful armed defense of their community,  the increasingly hostile atmosphere convinced many Black Atlantans to regroup on the Westside.",
        "mediaType" : "image",
        "date" : "October 7, 1906",
        "tags" : ["racism", "development"],
    },
    {
        "itemName": "Alonzo Herndon Family Home",
        "itemSubhead": "Economic Diversity in the Early 20th Century",
        "itemDescription": "The former home of Atlanta’s first Black millionaire, Alonzo Herndon, sits on the southern border of Vine City. Herndon arrived in 1883 and started a prosperous barbering business; he also invested in real estate and in 1905 founded the Atlanta Life Insurance Company, a crucial lifeline at a time when many white-owned companies refused policies to Blacks. Built in 1910, the Herndon family home harks back to an earlier era when the Westside housed residents from a mixture of economic backgrounds.",
        "mediaType" : "image",
        "date" : "1910",
        "tags" : ["racism", "activism"],
    },
    {
        "itemName": "The Impact of Redlining & Atlanta’s Racial Segregation Laws",
        "itemSubhead": "Government-Backed Racist Housing Policy",
        "itemDescription": "In the 1930s, the federal government commissioned and circulated a series of maps rating city neighborhoods by supposed mortgage lending risk. These maps specified four “grades,” with all African American residential areas, regardless of income, rated as the lowest, “D” (or “red”) neighborhoods – hence the term “redlining.”, Assessors classified Atlanta’s entire Westside as a high-risk area – setting in motion a self-fulfilling prophecy as banks subsequently refused to lend in the area. Moreover, local whites pursued similar efforts on the municipal level, passing racial segregation ordinances in 1913, 1916, 1929, and 1931 - despite Supreme Court rulings in 1917 and 1924 that such laws were unconstitutional.  Even though these particular attempts failed, it demonstrates how determined whites were to keep African Americans out of “their” neighborhoods.",
        "mediaType" : "image",
        "date" : "1938",
        "tags" : ["activism", "housing"],
    },
    {
        "itemName": "Fire in the Old Fourth Ward",
        "itemSubhead": "1917 Great Atlanta Fire",
        "itemDescription": "In 1917 The Great Atlanta Fire destroyed many homes on Auburn Avenue and in the 4th Ward, where most Black families lived up until then. This caused mass migration of Black families to the city’s Westside, one of the few areas in Atlanta where whites did not vigorously oppose Black settlement. Many Black families moved to Vine City and nearby areas.",
        "mediaType" : "image",
        "date" : "1917",
        "tags" : ["development", "housing"],
    },
    {
        "itemName": "Public Housing Developments Displace Residents",
        "itemSubhead": "Supposed “Slums” Demolished to Make Way for New Developments",
        "itemDescription": "Thousands of Black residents were displaced when the Atlanta Housing Authority started building public housing in the mid-1930s. As in virtually all American cities at the time, these housing projects were racially segregated, formally in the South but informally in the North prior to 1964.  Not all of the housing destroyed fit the description of “slums” that was used to justify these projects. This man, moving his family’s belongings prior to the opening of the Alonzo Herndon Homes in 1941, may have hauled ice for a living, small-scale entrepreneurship being a strategy some Black men successfully used to avoid racial discrimination in the workplace.  Black homeowners in the demolished areas typically did not receive fair market value for their homes, and faced the predicament of finding new housing in a segregated market with many areas off-limits to them.",
        "itemMedia":'<img class="content" src="images/33.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/33.jpg">',
        "mediaType" : "image",
        "date" : "1941",
        "tags" : ["activism", "housing"],
    },
    {
        "itemName": "Life on the Westside in the 1950's",
        "itemSubhead": "Myrtle Dansby, English Avenue Resident, Remembers the Neighborhood",
        "itemDescription": "Myrtle Dansby was one of the many Old Fourth Ward residents who moved to the Westside in the 1940’s. She has lived in the area for the last sixty-six years and recalls fond memories of the neighborhood in the 1950’s and 1960’s.",
        "mediaType" : "video",
        "date" : "1995",
        "tags" : ["racism", "development"],
    },
    {
        "itemName": "Changing Demographics",
        "itemSubhead": "Affordable Housing on the Westside: 1940's - 1960's",
        "itemDescription": "By 1930 Vine City and most of the Westside was majority-Black. Exceptions did exist – working class white families continued to live in the area through the 1940’s, especially in “Bellwood” (present day English Avenue) – but as increasing numbers of Black families moved to the area in the 1940's and 1950's, when all Black housing projects were built, white families continued to move out.",
        "mediaType" : "image",
        "date" : "1940",
        "tags" : ["racism", "housing"],
    },
    {
        "itemName": "Martin Luther King Jr. Leads Demonstrations for Fair Housing in Vine City",
        "itemSubhead": "Rising Tensions Result in Protests",
        "itemDescription": "In the 1960’s issues over racial discrimination across housing, services and infrastructure erupted in protests. Common issues facing Black families included: overpaying for sub-standard housing; absentee landlords ignoring tenants’ requests; lack of access to affordable and high quality food; and laws, policies and social practices that trapped Black families into the least desirable, low-lying parts of the city where poor drainage and sanitation problems were prevalent. Moreover, in Atlanta, the city refused to pave streets in Black neighborhoods into the 1950s and in the early twentieth century, even refused to pick up garbage. In 1966 Martin Luther King Jr. and Coretta Scott, who in 1965 had moved into a home at 239 Sunset Avenue in Vine City, led a protest in the neighborhood against the unsafe and unfair housing conditions.",
        "mediaType" : "image",
        "date" : "January 31, 1966",
        "tags" : ["development", "housing"],
    },
    {
        "itemName": "1960 English Avenue School Bombing",
        "itemSubhead": "Incident Underlines Tensions in the “City too Busy to Hate.”",
        "itemDescription": "This 1960 Chicago Tribune Coverage of the English Avenue School Bombing describes a horrific scene:<br>“Atlanta, Dec. 12 - A dynamite bomb blasted a Negro elementary school early today...The blast occurred hours before school opened and no one was injured. Sixteen hundred children attend the school. Police theorized that the bomb, composed of 10 sticks of dynamite, was thrown against the school from a passing car…”<br>“The school is in a middle class Negro neighborhood and within two block of white dwellings and 10 blocks from the Georgia Tech campus. There was speculation that the bombing was the work of groups fighting against mixing of the races in Atlanta's schools.”",
        "mediaType" : "image",
        "date" : "December 12, 1960",
        "tags" : ["racism", "activism"],
    },
    {
        "itemName": "Civil Rights Schisms Arise in the Mid-Late 60’s",
        "itemSubhead": "Diverse Activism in Vine City in the 1960’s and 70’s.",
        "itemDescription": "In the mid-1960’s not only were leaders from the Southern Christian Leadership Council (SCLC) and the Student Nonviolent Coordinating Committee (SNCC) active in the community, but area colleges and universities and early public-private initiatives such as the Council on Human Relations of Greater Atlanta, Inc. spearheaded projects as well. An example of such a project is the “Vine City Project: Experiments in Self Help” which paired area college students with community members to work on cleanup and other various self-directed projects\". Seen by many as a positive alternative to the more radical wings of the civil rights movement, these initiatives asked residents to do what they had been doing for generations: building and maintaining their own communities.",
        "mediaType" : "image",
        "date" : "January 31, 1966",
        "tags" : ["racism", "housing"],
    },
    {
        "itemName": "The Summerhill Riots",
        "itemSubhead": "Police Brutality Leads to Violent Protests",
        "itemDescription": "In 1966, after multiple incidents of police brutality in the all Black, working class neighborhood of Summerhill, and with tensions rising as planned urban renewal projects razed Black neighborhoods to build highways all around the city, a four-day protest erupted. Termed a riot by the media, the  four days of violence in Summerhill resulted in one death, multiple injuries and many arrests. Stokely Carmichael of the Student Nonviolent Coordinating Committee (SNCC) was accused of inciting the protests and the emerging militancy of the Black Power movement worried both white city leaders and more conservative Black leaders.",
        "itemMedia":'<img class="content" src="images/31.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/31.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Schisms Between Civil Rights Movement Groups Rise in the Mid-Late 60’s",
        "itemSubhead": "Multiple Community Development, Civil Rights and Black Power activist groups in Vine City in the 1960’s and 70’s.",
        "itemDescription": "In the mid-1960’s not only were leaders from the Southern Christian Leadership Council (SCLC) and the Student Nonviolent Coordinating Committee (SNCC) active in the community, but area colleges and universities and early public-private initiatives such as the Council on Human Relations of Greater Atlanta, Inc. spearheaded projects as well. An example of such a project is the “Vine City Project: Experiments in Self Help” which paired area college students with community members to work on cleanup projects and other “experiments” in community self directed development. Seen by many as a positive alternative to the more radical wings of the civil rights movement, these initiatives asked residents to do what they had been doing for generations: building and maintaining their own communities.",
        "itemMedia":'<img class="content" src="images/09.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/09.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Black Power in Atlanta",
        "itemSubhead": "The Black Panther Party Opens its Atlanta Office in Vine City",
        "itemDescription": "In early 1966 the Black Panther party opened an office in Vine City. According to Winston A. Grady-Willis in her book <i>Atlanta and Black Struggles for Human Rights</i>, the free breakfast program was a key component of the Atlanta office’s ability to recruit party members. Following the Summerhill incident, tensions in Vine City ran high. Similar to the national debates over the best tactics to promote Black liberation, the Panthers, church ministers, SCLC and other more conservative activist groups in Vine City argued about the right approach to change. This photograph of riots in Vine City in 1967 illustrates the rising frustrations of many young, Black Atlantans.",
        "itemMedia":'<img class="content" src="images/11.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/11.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Suburbanization & a Shrinking Population",
        "itemSubhead": "By the mid-1970’s middle class families were starting to leave the Westside",
        "itemDescription": "By the 1970s, federal fair housing laws were enabling affluent Black families to move into formerly white city neighborhoods as well as some suburbs. Deteriorating conditions in Vine City and English avenue upset middle class residents and families began leaving the area. By the 1990's, residents began to notice that families were leaving in droves. Rebecca Jackson, interviewed in the clip here as a part of the Booker T. Washington high school 1988 oral history project, grew up in Vine City and recalls the changes to the neighborhood that began with families, including her own, moving out. In 1960 Vine City’s population was close to 9,000 but by 1980 that number had dropped to just over 6,000.",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio5.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "The Development Train",
        "itemSubhead": "Atlanta’s Business Elite Construct a Convention Town",
        "itemDescription": "At least since the 1940s, Atlanta's Black and white political and business leadership had negotiated behind closed doors to manage racial unrest, during which time the development train rarely slowed down. In the 1960’s and 70’s hotels and gleaming office towers cropped up in Atlanta’s northern reaches and in 1966 the city got two professional sports teams when the Milwaukee Braves moved to Atlanta. Business leaders envisioned a downtown constructed primarily for business conventions and international travelers and worked with conservative state leaders to secure funding for the state-owned Georgia World Congress Center, which opened in 1976. Yet in 1973 the city also elected its first black mayor, Maynard Jackson. As the picture here illustrates, in the mid-1970’s the MARTA public transportation system connected Westside communities more directly to downtown Atlanta, yet did not provide anything resembling a comprehensive transit network that could have enabled access to the northern metro area where the most job growth was taking place.",
        "itemMedia":'<img class="content" src="images/32.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/32.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "“Delaying Conveniences” in the 1950’s",
        "itemSubhead": "Tillman Ward Discusses not having Hot Water or Television",
        "itemDescription": "Tillman Ward, interviewed here, grew up in Vine City right on the site of the present day Ashby Street MARTA station. Tilman’s father built the duplex himself, renting out one side to fund his children's college education. This scrimping for the benefit of future generations was a common experience in the neighborhood in the 1950’s and 60’s, used by many African American families to create housing that white developers were often unwilling to build.  Black owner-builders commonly saved money to buy vacant land, then gradually built their own houses as they could afford, often foregoing amenities like electricity in the meantime.  When owners could not complete the work themselves, they typically turned to Black building tradesmen like carpenters and masons, keeping economic gains within communities.",
        "itemMedia":'https://player.vimeo.com/video/145549665?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video02.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Westside Community Groups Successfully Fight Labor Building",
        "itemSubhead": "Westside Residents gleeful after winning a development fight with the city",
        "itemDescription": "In 1986, the Atlanta City Council voted to sell land in Vine City to the state to build a labor building. But community members did not want a labor building in their neighborhood and believed the vote and the sale of the land to be illegal; they filed a lawsuit in Fulton Superior Court and pushed for a re-vote. The Vine City Housing Ministry, a group of nearly a dozen churches who used their collective power to put pressure on the city, emerged during this time period in order to both support and temper the activism of the community. In many ways the grassroots activism and resistance of this moment mirror the fervor of the mid-1960s. A protest flyer in the spirit of James Baldwin’s famous quote that “urban renewal is negro removal” reminds residents: “This is the worst case yet of urban removal in the disguise of urban renewal...Vine City is alive and we intend to fight…”",
        "itemMedia":'<img class="content" src="images/13.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/13.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Resident speaking out against Dome at public meeting",
        "itemSubhead": "Eula Leake, 81, “Says Dome Might Upset Quiet Neighborhood”",
        "itemDescription": "At the same time community residents were fighting the labor building, another group of powerful businessmen, investors and political leaders were already negotiating over the same piece of land. As early as 1985, plans for the first Georgia Dome were underway in Atlanta. The idea was not only to give the Atlanta Falcons a new home but to also set the city up to be a competitive site for the 1996 Olympics. This 1987 photograph and article from the Atlanta Journal Constitution provides a glimpse into the development focus of the time, while revealing the writer’s assumptions about the neighborhood’s origins: “Because of its poverty, Vine City has been a thorn in the side of every city administration since at least the mid 1950’s. It is one of the city’s oldest black communities and, literally from the other side of the tracks, has supplied the doormen, maids, laborers, cashiers, cabbies, dishwashers and other laborers that have kept the city running for more than a century.”",
        "itemMedia":'<img class="content" src="images/14.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/14.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Church Leaders Band Together",
        "itemSubhead": "As Plans for the Dome Move Forward, Church Leaders Organized",
        "itemDescription": "During early discussions and plans for the first Georgia Dome the possibility of moving Mount Vernon Baptist Church and Friendship Baptist church, two historic Black churches was brought up. This prompted the leaders of these churches to call on pastors and ministers from all over the Westside to help them challenge the development. All-night vigils were held, the pastors threatened to stand in front of bulldozers and a widespread community response was mobilized. However, unlike the more grassroots approach to fighting the labor building, this group yielded its political power to ask for specific concessions and agreements, specifically provisions for high quality, affordable housing and a jobs training program. Meeting with city leaders behind closed doors, the ministers negotiated a deal hoping to ensure real community benefits from the project. In hindsight many such as Reverend Cottrell wonder whether this was a wise decision but at the time it felt like the only option.",
        "itemMedia":'https://player.vimeo.com/video/145558085?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video05.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "“They Trusted No One in the City”",
        "itemSubhead": "Reverend Cottrell explains the changing activist landscape",
        "itemDescription": "Reflecting back on the mid 1980’s, Reverend Cottrell outlines the reasons he thinks that community activists fought the labor building and how the church took a supporting role during these struggles. When the debate over construction of the first Georgia Dome emerged soon after the labor building controversy, church leadership got in front of the struggle and led most of the action. With church leaders at the head of the struggle the negotiations became less about shutting down the development of the Dome—they saw that as inevitable—and more focused on negotiating agreements that would benefit the wider Vine City area.",
        "itemMedia":'https://player.vimeo.com/video/145562439?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Suburbanization & Population Loss",
        "itemSubhead": "By the mid-1970’s middle class families were starting to leave the Westside",
        "itemDescription": "By the 1970s, federal fair housing laws were enabling affluent Black families to move into formerly white city neighborhoods as well as some suburbs. Deteriorating conditions in Vine City and English avenue upset middle class residents who began leaving the area. By the 1990's, residents began to notice that families were leaving in droves. Rebecca Jackson, interviewed in the clip here as a part of the Booker T. Washington high school 1988 oral history project, grew up in Vine City and recalls the changes to the neighborhood that began with families, including her own, moving out. In 1960 Vine City’s population was nearly 9,000 but by 1980 that number had dropped to just over 6,000.",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio5.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "Political Maneuverings",
        "itemSubhead": "July, 1988: State, County and City Argue over the Terms of the Dome",
        "itemDescription": "The first Georgia Dome deal was spearheaded by a group of investors, the “Stadium Corporation,” with support from the board of the Georgia World Congress Center. While the Dome was ultimately built on what the state considered “abandoned railroad land,” the expansion of the World Congress Center, which was wrapped up in the deal, included the use of eminent domain to seize and raze 126 homes in the Lightning Community and relocate those families. The community was outraged, as were the churches and prominent members of city council who also spoke up against the early plans. In response, a ten million dollar trust fund was set up to help build affordable housing in the area. Many were still upset about the agreement but plans proceeded. While many governing bodies had roles to play in the stadium deal, this interview with then-Fulton County Commissioner Nancy Boxill focuses  on the state’s. The financing for the estimated $158 million needed to build the Dome required that 1/3 of the cost come from the city and county hotel-motel tax.",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio2.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "The City Council Votes",
        "itemSubhead": "In August, 1988 the city approved the Dome but they listed a number of stipulations.",
        "itemDescription": "As the Atlanta Daily World reported, the council voice “bellowed loud and clear: “you can build the Dome providing you do your part in taking care of the residents of Vine City.” The city council’s 1998 stipulations included:<ul><li>A surcharge of 25 cents to $1 on tickets to stadium events to augment the ten million dollar trust fund</li><li>Any money left over after the stadium’s expected operating deficit would go back to the city</li><li>The city would not have to pay for infrastructure around the Dome</li><li>The Stadium Corporation would be required to ensure that 35% of the people working on the construction of the Dome were minorities</li><li>20% of supplies bought for operations after the stadium opens must be purchased from minority firms</li><ul>",
        "itemMedia":'<img class="content" src="images/15.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/15.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Compromise after Political Pressure",
        "itemSubhead": "Final Approval for the Dome Scraps Stipulations",
        "itemDescription": "On two successive days in June, 1989, after the state had approved the Dome – with few of the city’s original stipulations remaining in the deal -- the city council and Fulton County voted unanimously in favor of building the Dome. This was the result of compromise and pressure from the state and was representative of the back room political maneuverings typical of Atlanta development politics. As the Atlanta Daily World reported: “Disagreements over the project last week led to reports the stadium would not be built, but civic leaders spent the weekend settling disputes.” After the Fulton County vote, then chairmen of the commission and mayor hopeful Michael Lomax exclaimed, “The Dome is done. Long live the Dome!”",
        "itemMedia":'<img class="content" src="images/16.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/16.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Vine City Residents Question the Dome",
        "itemSubhead": "At the Community Level Many Felt Betrayed by the Process",
        "itemDescription": "Despite the leverage of various Black city council members and church leaders, many Vine City residents, especially the residents of Lightning, were not pleased about the Dome. Haniyfa Ali, a community activist from Lightning, told reporters: “We don’t need to sell out Vine City for ten million dollars.” This 1988 AJC photo is of Dorothy Bolden, a Vine City resident who told city officials that they were all “praying that they could keep their homes.”",
        "itemMedia":'<img class="content" src="images/17.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/17.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Ivory Young Discusses the “Taking” of Lightning",
        "itemSubhead": "Looking Back on What Happened ",
        "itemDescription": "In 2015 Councilmen Young was interviewed about his memory of the 1992 Georgia Dome. Councilman Young worked for the architectural and construction firm that designed and managed the construction of the 150 homes that were to be built using the ten million dollar trust fund. He looks back on the way that the 1992 Dome negotiation took place, reflecting with dismay over the injustice of what happened to the community of Lightning.",
        "itemMedia":'https://player.vimeo.com/video/145779833?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/18.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Hopes for Affordable Housing in Vine City",
        "itemSubhead": "By 1990 Work Had Begun on Affordable Housing Units Tied to Stadium Agreement",
        "itemDescription": "In May of 1990, groundbreaking for the 150 planned single-family houses in Vine City began. Ultimately, most of the funding for the trust fund came from the city and the county, with two million dollars promised from private funds to be raised by the Stadium Corporation. While the homes were relatively affordable, homeowners had to qualify for the $55,000 mortgage and have an income of about $17,000 a year. Plans were to complete construction of the houses over the next 3 years and as this picture shows, construction began immediately. ",
        "itemMedia":'<img class="content" src="images/19.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/19.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Selling 150 Affordable Housing Units Proves Difficult",
        "itemSubhead": "Housing Ministry Finding Few Who Qualify for Low-Price Homes",
        "itemDescription": "Optimism about the 150 affordable units started to wane by October 1990 when the 11 churches working together under the Vine City Housing Ministry reported  they had only been able to sell 1 of the 5 houses constructed. Much of this had to do with the relative poverty of neighborhood residents and the fact that even “affordable” housing was out of reach for them. As the Atlanta Journal Constitution reported: “Of the 400 applications distributed, 300 were returned but only 1 qualified.” The problems were also tied to market logic. Trying to sell new houses that cost $40,000 - $60,000 right next to vacant lots or old homes that had been sitting empty for decades proved a challenge.",
        "itemMedia":'<img class="content" src="images/20.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/20.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Disputing the Blame Placed on the Vine City Housing Ministry",
        "itemSubhead": "In a 2015 Interview Rev. Cottrell Disputes that Housing Ministry was at Fault",
        "itemDescription": "The October 1990 problems with building housing were only a small indication of the troubles to come. The Vine City Housing Ministry not only faced challenges selling and financing the houses, but since they did not have expertise in the building trades, they also had trouble managing their role as community developers. Meanwhile, city, state and county officials and the various investors in the project also played roles: advising the ministry, selecting developers and checking in on their progress. The historical record shows a complex web of decision-making. Moreover, structural factors, such as racist lending policies, metropolitan expansion and the departure of more fortunate residents from Vine City, made sales in the area difficult. However, the contemporary story about what happened places most of the blame on the churches and community developers. In this recent interview, Reverend Cottrell challenges the media interpretation that failure was entirely the fault of the Ministry.",
        "itemMedia":'https://player.vimeo.com/video/145780308?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "1988 Dome Oral History Project interviewer, Looks Back",
        "itemSubhead": "Byron Amos Reflects on the Problems with the 1990’s Approach to Housing",
        "itemDescription": "Byron Amos was a Booker T. Washington sophomore in 1988.  His is one of the clearest voices interviewing residents and asking tough questions of politicians in the 1988-89 oral history project.  In this 2015 interview Amos reflects on what he learned from the 1988 oral history project, specifically the aftermath of the housing fund.",
        "itemMedia":'https://player.vimeo.com/video/145780566?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/21.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "The Color of Money",
        "itemSubhead": "The Atlanta Journal Constitution Exposes Widespread Racist Lending",
        "itemDescription": "Another challenge faced by the Vine City Housing Ministry that the media did not discuss was racially discriminatory lending policies, still prevalent in the late 1980’s and early 1990’s. In 1989 the Atlanta Journal Constitution ran a Pulitzer Prize-winning series called <i>The Color of Money</i>, which investigated the impact of race on lending practices in the city of Atlanta. The report uncovered sad truths about lending practices and put into context the severe economic and social challenges facing Black families in the city. As the maps here show, the Westside communities were at the heart of this structural problem.",
        "itemMedia":'<img class="content" src="images/22.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/22.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Demolition of Public Housing in Atlanta",
        "itemSubhead": "Starting in 1994 the Atlanta Housing Authority began demolishing public housing projects",
        "itemDescription": "Based on the perception that public housing was a failure, and fueled by funds from the U.S. Department of Housing and Urban Development's Hope VI, the Atlanta Housing Authority adopted a plan to replace low-income public housing projects with mixed income communities.  The Housing Authority received the first pilot grant in 1993.  Begun in 1994, the demolition continued through 2011.  While there have been some successes with the model of mixed income communities, Deirdre Oakley, assistant professor at Georgia State, has done a study that suggests that many residents have been relocated to neighborhoods that are not significantly better than those they left and most of the housing is from the private rental market which does not guarantee availability to low income residents.",
        "itemMedia":'<img class="content" src="images/23.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/23.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "1996 Olympics",
        "itemSubhead": "In spite of promises, the Olympic Games did not bring improvements to the Westside",
        "itemDescription": "The city used eminent domain  to demolish homes in order to accommodate the expansion of the Dome area to provide venues and parking for the 1996 Olympics.  Although the city made much of public/private partnerships to improve the neighborhoods around Olympic Park, residents once again felt let down by the gap between the promises made and the outcome of events. This picture is of Columbus Ward, long-time community activist in the neighborhoods just south of the Westside Peoplestown, Mechanicsville and Summerhill, where two Domes and Olympic-era development made similar promises of urban redevelopment. Ward questions whether the television coverage of the Olympics would also zoom in on the living conditions in the neighborhoods around the stadiums. ",
        "itemMedia":'<img class="content" src="images/29.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/29.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Vine City Residents Not Pleased About Dome",
        "itemSubhead": "At the Community Level Many Residents Felt Betrayed by the Process",
        "itemDescription": "Despite the leverage of various Black city council members and church leaders, many Vine City residents, especially the residents of Lightning, were not pleased about the Dome. Haniyfa Ali, a community activist from Lightning, told reporters: “We don’t need to sell out Vine City for ten million dollars.” This 1988 AJC photo is of Dorothy Bolden, a Vine City resident who told city officials that they were all “praying that they could keep their homes.” ",
        "itemMedia":'<img class="content" src="images/17.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/17.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Under Water: A Flood, Tornado and the Great Recession",
        "itemSubhead": "1997-2008: Hardship on the Westside",
        "itemDescription": "After the excitement of the 1996 Olympics receded, residents of the Westside noticed little economic benefit from the influx of money that came in during the surge of development. Instead, by 2001 another jobs recession was hurting the area and a housing boom was spurring bricks and mortar investment but little substantial change. In 2002, a massive flood put parts of the Westside under six feet of water. When the Great Recession hit in late 2007 and the housing bubble burst, buildings and houses built during the boom were left empty. Homeowners were underwater on mortgages (many of which were fraudulent) and renters were evicted from homes owned by absentee landlords. The area was again plagued by water damage when a 2008 tornado hit and residents were reminded of how living in  one of the city’s lowest lying areas could have dangerous consequences.",
        "itemMedia":'<img class="content" src="images/27.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/27.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Foreclosure Crisis and Occupy our Homes in Vine City",
        "itemSubhead": "New Pockets of Activism and Resistance",
        "itemDescription": "The 2008 foreclosure crisis hit the United States hard. Between 2007 and today, more than 5 million American households have experienced foreclosure. This waterfall of foreclosures, disproportionately impacted working and middle class Americans, particularly people of color. And a number of the mortgages and evictions were fraudulent. With fraud also came resistance and activism. Atlanta’s Occupy Our Homes emerged from the Occupy and housing justice movements to help working class Atlantans fight for the right to fair housing. In 2012 the group helped the Higher Ground Empowerment Center, a historic church in Vine City, and a Vine City homeowner, win the right to stay in their church and home. Part of the post-Occupy resurgence of direct action, Occupy Our Homes Atlanta shows that new pockets of activism can crop up and shift the activist landscape, even if only momentarily. ",
        "itemMedia":'<img class="content" src="images/24.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/24.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Plans for a New Georgia Dome",
        "itemSubhead": "Falcons’ Announcement Spurs  Controversy ",
        "itemDescription": "In the summer of 2010 Falcons owner Arthur Blank and his executive team began private meetings with elected officials to make known their desire for a new, open-air stadium.  Elected officials were torn. The legacy of the benefits to the city, and especially to the neighborhoods right around the first Dome, were not great and a massive amount of public dollars would be needed to finance a new stadium. By 2012, after the pricetag had gone up considerably and a public survey revealed that 75% of Atlantans were against the Dome, Georgia state Senator Vincent Fort wrote an opinion piece in the Atlanta Journal Constitution communicating regret about voting to help finance the dome: “Is public funding of sports teams -- bonding support or other direct taxes -- a legitimate municipal or state government undertaking?...I say let the Falcons and the NFL finance their own facility. It would be better to use hundreds of millions of taxpayer dollars to improve education as an economic driver than to support a sports team owner.”",
        "itemMedia":'<img class="content" src="images/25.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/25.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "A New Round of Promises",
        "itemSubhead": "Along with the Controversy came Negotiations over Community Benefits",
        "itemDescription": "Having learned their lesson from the public outcry during the negotiations over the 1992 Dome, policymakers and the Arthur Blank Foundation set up a  community benefits committee ahead of time, selecting specific neighborhood leaders from Vine City, English Avenue and Castleberry Hill to participate, and helping to outline the scope of the projects that would be funded through the process. Yet despite promises to give $30 million to support workforce development, public safety, education and more, community residents and supporters question whether this was enough and are skeptical about whether there will be a return on the public’s investment. In this video clip Hattie Dorsey, founder and former president of the Atlanta Neighborhood Development Partnership (ANDP), questions the community benefits process and the financing model of the funds promised to the Westside. ",
        "itemMedia":'https://player.vimeo.com/video/145888554?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video05.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Controversy over the New Georgia Dome",
        "itemSubhead": "In 2010 The Falcons Announce plans for a new Dome & Controversy Emerges",
        "itemDescription": "In the summer of 2010 Falcons owner Arthur Blank and his executive team began private meetings with elected officials to make known their desire for a new, open-air stadium.  Elected officials were torn. The legacy of the benefits to the city, and especially to the neighborhoods right around the dome, were not great and a massive amount of public dollars would have to help finance the dome. By 2012, after the pricetag had gone up considerably and a public survey revealed that 75% of Atlantans were against the Dome, Georgia Senator Vincent Fort wrote an opinion piece in the Atlanta Journal Constitution saying that he regretted voting to help finance the dome: “Is public funding of sports teams -- bonding support or other direct taxes -- a legitimate municipal or state government undertaking?...I say let the Falcons and the NFL finance their own facility. It would be better to use hundreds of millions of taxpayer dollars to improve education as an economic driver than to support a sports team owner.”",
        "itemMedia":'<img class="content" src="images/25.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/25.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Residents Skeptical about new Georgia Dome’s Promises",
        "itemSubhead": "Residents not Included in the Debate also have a Stake",
        "itemDescription": "Along with policymakers and leaders, the residents of the Westside, who have lived and worked to make these neighborhoods better over the years have a stake in helping to shape the future. In a 2013 long-form piece on the new stadium in the Atlanta Magazine called “It’s going to take more than $45 million* to help Vine City,” Greg Hawthorne, current executive director of the Vine City Health and Housing Ministry” told reporters that the community benefits “really needs to translate into what the community needs. Jobs. Not just minimum wage jobs, but living wage jobs.” <br>Residents themselves, and not just the ones usually representing community at meetings or being interviewed by the media have ideas about what needs to happen and vested interests in seeing change occur. In this 2015 interview, Sandra Walker, who has lived in the Westside since birth talks about why she remains living there. Echoing the worries of many residents, she says that she is concerned that not only will the new Dome not help the neighborhood but that the plans are to push current residents out. ",
        "itemMedia":'https://player.vimeo.com/video/145885412?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/26.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "2017 Dome Supporters",
        "itemSubhead": "Some argue that a new Falcons Stadium will Catalyze Change",
        "itemDescription": "Many, such as Councilman Ivory Young interviewed here, are optimistic that the new Georgia Dome and the plans for community redevelopment connected to it will bring positive change to the area. Young focuses on the tension between raising taxes and working to bring in more dollars through tourism and other economic generators. He challenges a Brookings Institute study arguing that stadiums are not positive economic drivers for cities and instead focuses on the jobs that new development such as the stadium and the Walmart bring to the area. Unfortunately, as he acknowledges, these jobs are not providing living wage jobs to residents but he believes that for now they are the best option that he can work to provide his constituents, to offset some of the educational inequities facing Westside residents. ",
        "itemMedia":'https://player.vimeo.com/video/145940863?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/18.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "2017 Georgia Dome – Georgia Supreme Court Case",
        "itemSubhead": "English Avenue and Vine City Residents take the City to Court",
        "itemDescription": "In February 2014, when the Georgia legislature voted to validate the use of bonds tied to the Fulton County hotel-motel tax to finance the Georgia Dome, a group of English Avenue and Vine City residents filed objections. The residents, Mamie Moore, Reverend W.L. Cottrell, Tracy Bates, John H. Lewis III and Joe Henry Beasley then embarked on a more than a year long legal battle ending in a loss at the Georgia Supreme Court. The group argued that the 2010 state law authorizing extension of the existing Atlanta hotel-motel tax was unconstitutional and that the city’s development wing, Invest Atlanta, was not legally allowed to issue revenue bonds for property that they do not own. The Georgia Supreme Court did not rule in the residents’ favor and claimed that the hotel-motel tax could be used to fund the stadium because the city and county would “directly benefit from an increase in tourism” from the Dome. This statement was made despite widespread agreement amongst U.S. economists that stadiums do not directly increase city revenues. In this 2015 interview, Mother Moore, one of the parties in the lawsuit, outlines her reasons for pursuing this legal action. ",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio4.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "Learning from these Histories to Shape the Future",
        "itemSubhead": "Looking Back to help Shape a Better Future",
        "itemDescription": "Today, Atlanta’s Westside is again in a period of intense development and neighborhood groups are organizing in response. Georgia Tech is extending their campus into the area; the Atlanta Housing Authority recently received a thirty million dollar award from HUD to rebuild mixed-income housing at the sites of former housing development projects; the Atlanta Beltline Inc. is promising to build up the Westside trail; the Blank Foundation, Chik-Fil-A Foundation and Invest Atlanta are embarking on a “place-based” approach to redevelopment along with the recently created Westside Future Fund, a nonprofit established and led by mayor Kasim Reed, high-powered Atlanta CEO’s and university presidents, which promises to coordinate the planning, fund-raising and revitalization efforts across the Westside. As past waves of development, housing construction and community-based resistance and activism have shown, the success or failure of future attempts at change making depend on many factors, a number of them deeply connected to sweeping structural and historical mechanisms outside of any one group’s control. Listening to and learning about the ways that structural forces have impacted the lived experiences, memories, hopes and dreams of English Avenue and Vine City residents is a central component of learning from history. It is our hope that this exhibit has helped, in some small way, contribute to this effort.",
        "itemMedia":'https://player.vimeo.com/video/125575280?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/28.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Two line name, 30 characters",
        "itemSubhead": "Two line subhead, 37 characters limit",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placerholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Name Here",
        "itemSubhead": "Subheadline here",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },

]